apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-external-service
  labels:
    app: django-messaging-app
spec:
  selector:
    app: django-messaging-app
    version: v1.0 # current version is the blue
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
